import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const messageItemStyle = TextStyle(color: Colors.black, fontSize: 16, fontWeight: FontWeight.w400);
const titleStyle = TextStyle(color: Colors.black, fontSize: 18, fontWeight: FontWeight.w700);
const titleMediumStyle = TextStyle(color: Colors.black, fontSize: 16, fontWeight: FontWeight.w700);
const titleSmallStyle = TextStyle(color: Colors.black, fontSize: 14, fontWeight: FontWeight.w600);
const titleSmallBlueStyle = TextStyle(color: Colors.blueAccent, fontSize: 14, fontWeight: FontWeight.w700);
const titleMediumBlueStyle = TextStyle(color: Colors.blueAccent, fontSize: 16, fontWeight: FontWeight.w700);
const titleExtraMediumBlueStyle = TextStyle(color: Colors.blueAccent, fontSize: 24, fontWeight: FontWeight.w700);
const titleBigBlueStyle = TextStyle(color: Colors.blueAccent, fontSize: 32, fontWeight: FontWeight.w700);
const smallWhiteStyle = TextStyle(color: Colors.white, fontSize: 14, fontWeight: FontWeight.w700);
const mediumWhiteStyle = TextStyle(color: Colors.white, fontSize: 20, fontWeight: FontWeight.w700);
const hintMediumStyle = TextStyle(color: Colors.grey, fontSize: 16, fontWeight: FontWeight.w700);
const hintStyle = TextStyle(color: Colors.grey, fontSize: 18, fontWeight: FontWeight.w600);
const hintSmallStyle = TextStyle(color: Colors.grey, fontSize: 14, fontWeight: FontWeight.w600);
const hintSmallPlusStyle = TextStyle(color: Colors.grey, fontSize: 12, fontWeight: FontWeight.w600);
const hintExtraSmallStyle = TextStyle(color: Colors.grey, fontSize: 10, fontWeight: FontWeight.w400);
const profileAttributeStyle = TextStyle(color: Colors.grey, fontSize: 16, fontWeight: FontWeight.w400);
const profileHintStyle = TextStyle(color: Colors.grey, fontSize: 16, fontWeight: FontWeight.w600);
const profileInputStyle = TextStyle(color: Colors.black, fontSize: 16, fontWeight: FontWeight.w600);
const profileDescriptionStyle = TextStyle(fontSize: 13);
const textStyle = TextStyle(fontSize: 16, fontWeight: FontWeight.w400);
const textSmallStyle = TextStyle(fontSize: 14, fontWeight: FontWeight.w400);
const previewRateStyle = TextStyle(color: Colors.black, fontSize: 14, fontWeight: FontWeight.w600);
const previewNameStyle = TextStyle(color: Colors.black, fontSize: 16, fontWeight: FontWeight.w700);
const serviceTitleStyle = TextStyle(color: Colors.black, fontSize: 14, fontWeight: FontWeight.w600);
const commentTextStyle = TextStyle(color: Colors.black, fontSize: 14, fontWeight: FontWeight.w400);
const serviceSubtitleStyle = TextStyle(fontSize: 12, fontWeight: FontWeight.w500);
const recordButtonStyle = TextStyle(fontSize: 16, color: Colors.white, fontWeight: FontWeight.w500);
const commentHintStyle = TextStyle(fontSize: 12, color: Colors.black, fontWeight: FontWeight.w400);
const errorStyle = TextStyle(fontSize: 12, color: Colors.redAccent, fontWeight: FontWeight.w400);
